Eye movement
tkuramot/cub3d pull request #29
Opened 2023-11-18 06:59 UTC by kaaaaakun

2023-11-18 07:06 UTC, kaaaaakun commented
やらなきゃいけないこと
・キーフックを設定する
・defineで1クリックでどのくらい方向変更するか決める
・回転行列・回転ベクトルの勉強
[参考](https://lodev.org/cgtutor/raycasting2.html)

2023-11-19 06:04 UTC, kaaaaakun commented
できたけど、W・Sの時だけ左右の移動が反転してしまう。ので、理由を検証する

2023-11-19 12:31 UTC, kaaaaakun commented on src/game/init_player.c
> -// Exit this program when an error occurs
ここにエラーの状態で入ってくることはないはずなので、エラー処理はしてません！

2023-11-19 13:18 UTC, tkuramot commented
ちゃんと回転できててすごい〜
壁関係のバグ治してくれてありがと！！

2023-11-20 12:05 UTC, tkuramot requested changes

2023-11-20 13:18 UTC, tkuramot commented on include/game.h
> +void	move_eye_movement(t_world *world, int rotate_direction);
よさそう！

2023-11-21 09:24 UTC, tkuramot approved these changes
めっちゃいい！

2023-11-21 09:24 UTC, merged